from enum import Enum
from typing import List

__all__ = (
    "ACTIONS_GENERATE_HASH_AND_PEPPER",
    "ACTIONS_VALIDATE_CREDENTIALS",
    "ACTIONS_GENERATE_MNEMONIC",
    "ACTIONS_SHIELD_MNEMONIC",
)

__prefix__ = "ACTIONS_"

ACTIONS_GENERATE_HASH_AND_PEPPER = "generate_hash_and_pepper"
ACTIONS_VALIDATE_CREDENTIALS = "validate_credentials"
ACTIONS_GENERATE_MNEMONIC = "generate_mnemonic"
ACTIONS_SHIELD_MNEMONIC = "shield_mnemonic"


ActionsDict = {
    "ACTIONS_GENERATE_HASH_AND_PEPPER": ACTIONS_GENERATE_HASH_AND_PEPPER,
    "ACTIONS_VALIDATE_CREDENTIALS": ACTIONS_VALIDATE_CREDENTIALS,
    "ACTIONS_GENERATE_MNEMONIC": ACTIONS_GENERATE_MNEMONIC,
    "ACTIONS_SHIELD_MNEMONIC": ACTIONS_SHIELD_MNEMONIC,
}


class ActionsEnum(str, Enum):
    GENERATE_HASH_AND_PEPPER = ACTIONS_GENERATE_HASH_AND_PEPPER
    VALIDATE_CREDENTIALS = ACTIONS_VALIDATE_CREDENTIALS
    GENERATE_MNEMONIC = ACTIONS_GENERATE_MNEMONIC
    SHIELD_MNEMONIC = ACTIONS_SHIELD_MNEMONIC


def __dir__() -> List[str]:
    return sorted(list(__all__))  # pragma: no cover
