ARG BASE_IMAGE=public.ecr.aws/amazonlinux/amazonlinux:2

FROM $BASE_IMAGE

RUN yum install python3 gcc net-tools -y

WORKDIR /app

COPY libnsm.so ./
COPY requirements.txt ./

RUN pip3 install -r requirements.txt

RUN mkdir ./enums
COPY enums/ ./enums/
COPY *.py ./
COPY run.sh ./

RUN for unit_test in *.test.py; do python3 $unit_test; done

RUN chmod +x run.sh
CMD ["/app/run.sh"]